name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '27.1.1'

      - name: Install dependencies
        run: mix deps.get

      - name: Run formatter check
        run: mix format --check-formatted --dry-run

      - name: Run security audit
        run: mix deps.audit

      - name: Compile the project
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
